"""empty message

Revision ID: b60eeeb8f64a
Revises: ffd37e204f75
Create Date: 2017-12-02 10:39:21.088152

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b60eeeb8f64a'
down_revision = 'ffd37e204f75'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('element', sa.Column('category', sa.String(length=50), nullable=True))
    op.drop_column('element', 'status')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('element', sa.Column('status', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_column('element', 'category')
    # ### end Alembic commands ###
